[project]
name = "03-deep-dive-into-openai-agents-sdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai-agents>=0.0.17",
    "pydantic>=2.11.5",
    "python-dotenv>=1.1.0",
]
